# Generated by Django 4.2.2 on 2023-07-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Start Date')),
                ('date_until', models.DateTimeField(verbose_name='Until Date')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company', verbose_name='Company')),
            ],
        ),
    ]
