# Generated by Django 4.2.2 on 2023-07-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_availableblock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableblock',
            name='color',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='availableblock',
            name='date_start',
            field=models.TimeField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='availableblock',
            name='date_until',
            field=models.TimeField(verbose_name='Until Date'),
        ),
    ]
