# Generated by Django 4.2.2 on 2023-07-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(verbose_name='Start Date')),
                ('date_until', models.DateTimeField(verbose_name='Until Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('state', models.CharField(choices=[('unassigned', 'Un Assigned'), ('assigned', 'Assigned'), ('done', 'Done'), ('canceled', 'Canceled')], max_length=25, verbose_name='State')),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
            },
        ),
    ]
