# Generated by Django 4.2.2 on 2023-07-08 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_availableblock_color_and_more'),
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.CreateModel(
            name='ProccessCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('done', 'Done'), ('cancel', 'Canel')], max_length=10, verbose_name='State')),
                ('date_start', models.DateField(verbose_name='Start Date')),
                ('date_until', models.DateField(verbose_name='Until Date')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.company')),
            ],
            options={
                'verbose_name': 'ProccessCreate',
                'verbose_name_plural': 'ProccessCreates',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='create_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='appointment.proccesscreate'),
        ),
    ]
