# Generated by Django 4.2.2 on 2023-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_appointment_archived_proccesscreate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proccesscreate',
            name='state',
            field=models.CharField(choices=[('draft', 'Draft'), ('done', 'Done'), ('cancel', 'Canel')], default='draft', max_length=10, verbose_name='State'),
        ),
    ]
