# Generated by Django 4.2.2 on 2023-07-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_alter_proccesscreate_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='state',
            field=models.CharField(choices=[('unassigned', 'Un Assigned'), ('assigned', 'Assigned'), ('done', 'Done'), ('canceled', 'Canceled')], default='unassigned', max_length=25, verbose_name='State'),
        ),
    ]
