# Generated by Django 4.2.2 on 2023-07-09 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
        ('appointment', '0004_alter_appointment_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='partner.partner'),
        ),
    ]
