# Generated by Django 4.2.2 on 2023-07-12 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('appointment', '0006_alter_appointment_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='partner',
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='customer.customer'),
        ),
    ]
