name: Docker Image CI

on:
  push:
    branches:
      - main
      - qa
      - dev
  pull_request:
    branches:
      - main
      - qa
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: bash deploy.sh -e ci -c build

      - uses: actions/checkout@v4
      - name: Up docker services
        run: bash deploy.sh -e ci -c 'up -d'
      
      - uses: actions/checkout@v4
      - name: Test django
        run: bash deploy.sh -e ci -c 'exec web python manage.py test'
      

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: bash deploy.sh -e ci -c build
